#pragma once

#include <windows.h>

enum LangType { L_TEXT, L_PHP, L_C, L_CPP, L_CS, L_OBJC, L_JAVA, L_RC,
    L_HTML, L_XML, L_MAKEFILE, L_PASCAL, L_BATCH, L_INI, L_ASCII, L_USER,
    L_ASP, L_SQL, L_VB, L_JS, L_CSS, L_PERL, L_PYTHON, L_LUA,
    L_TEX, L_FORTRAN, L_BASH, L_FLASH, L_NSIS, L_TCL, L_LISP, L_SCHEME,
    L_ASM, L_DIFF, L_PROPS, L_PS, L_RUBY, L_SMALLTALK, L_VHDL, L_KIX, L_AU3,
    L_CAML, L_ADA, L_VERILOG, L_MATLAB, L_HASKELL, L_INNO, L_SEARCHRESULT,
    L_CMAKE, L_YAML, L_COBOL, L_GUI4CLI, L_D, L_POWERSHELL, L_R, L_JSP,
    L_COFFEESCRIPT, L_JSON, L_JAVASCRIPT, L_FORTRAN_77, L_BAANC, L_SREC,
    L_IHEX, L_TEHEX, L_SWIFT, L_ASN1, L_AVS, L_BLITZBASIC, L_PUREBASIC,
    L_FREEBASIC, L_CSOUND, L_ERLANG, L_ESCRIPT, L_FORTH, L_LATEX,
    L_MMIXAL, L_NIM, L_NNCRONTAB, L_OSCRIPT, L_REBOL,
    L_REGISTRY, L_RUST, L_SPICE, L_TXT2TAGS, L_VISUALPROLOG,
    L_TYPESCRIPT, L_JSON5, L_MSSQL, L_GDSCRIPT, L_HOLLYWOOD,
    L_GOLANG, L_RAKU, L_TOML, L_SAS, L_ERRORLIST,
    L_EXTERNAL };

#define NPPMSG (WM_USER + 1000)
#define NPPM_GETCURRENTSCINTILLA (NPPMSG + 4)
#define NPPM_GETCURRENTLANGTYPE (NPPMSG + 5)
#define NPPM_GETNBOPENFILES (NPPMSG + 7)
#define ALL_OPEN_FILES 0
#define PRIMARY_VIEW 1
#define SECOND_VIEW 2
#define NPPM_MODELESSDIALOG (NPPMSG + 12)
#define MODELESSDIALOGADD 0
#define MODELESSDIALOGREMOVE 1
#define NPPM_GETPLUGINSCONFIGDIR (NPPMSG + 46)
#define NPPM_GETNPPVERSION (NPPMSG + 50)
#define NPPM_GETCURRENTBUFFERID (NPPMSG + 60)
#define NPPM_GETFULLPATHFROMBUFFERID (NPPMSG + 58)
#define NPPM_GETBUFFERIDFROMPOS (NPPMSG + 59)
#define NPPM_GETPOSFROMBUFFERID (NPPMSG + 57)
#define NPPM_GETCURRENTDOCINDEX (NPPMSG + 23)
#define MAIN_VIEW 0
#define SUB_VIEW 1
#define NPPM_GETCURRENTVIEW (NPPMSG + 88)
#define NPPM_SETMENUITEMCHECK (NPPMSG + 40)
#define NPPM_DMMSHOW (NPPMSG + 30)
#define NPPM_DMMHIDE (NPPMSG + 31)
#define NPPM_DMMUPDATEDISPINFO (NPPMSG + 32)
#define NPPM_DMMREGASDCKDLG (NPPMSG + 33)
#define NPPM_DMMVIEWOTHERTAB (NPPMSG + 35)
#define NPPM_ALLOCATECMDID (NPPMSG + 81)
#define NPPM_ADDTOOLBARICON_FORDARKMODE (NPPMSG + 101)
#define NPPM_ISDARKMODEENABLED (NPPMSG + 107)
#define NPPM_DARKMODESUBCLASSANDTHEME (NPPMSG + 112)
#define NPPM_GETPLUGINHOMEPATH (NPPMSG + 97)

#define NPPN_FIRST 1001
#define NPPN_READY (NPPN_FIRST + 1)
#define NPPN_BUFFERACTIVATED (NPPN_FIRST + 2)
#define NPPN_FILESAVED (NPPN_FIRST + 6)
#define NPPN_DARKMODECHANGED (NPPN_FIRST + 7)
#define NPPN_SHUTDOWN (NPPN_FIRST + 8)
#define NPPN_BUFFERDELETED (NPPN_FIRST + 18)
